# Generated by Django 6.0.7 on 2026-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_user_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
